In [1]:
import numpy as np


In [10]:
ar1 = np.array([1, 2, 3, 4])
ar2 = np.array([5, 6, 7, 8])


In [ ]:
#ADDITION
ar1 + ar2 

array([ 6,  8, 10, 12])

In [ ]:
#SUBTRACTION
result = ar1 - ar2 
result 

array([-4, -4, -4, -4])

In [ ]:
#DIVISION 
ar1 / ar2 

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [14]:
ar1 * ar2 

array([ 5, 12, 21, 32])

In [15]:
ar1 ** ar2 

array([    1,    64,  2187, 65536])

In [17]:
np.sum((ar1, ar2), axis=1)

array([10, 26])

In [19]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
b = np.arange(11, 20).reshape(3, 3)
b 

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [24]:
np.sum((a, b), axis=1)

array([[12, 15, 18],
       [42, 45, 48]])

In [ ]:
#ADDITION 
a + b 

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
#SUBTRACTION
a - b 

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [29]:
#MEAN
np.mean((a, b), axis=1)

array([[ 4.,  5.,  6.],
       [14., 15., 16.]])

In [33]:
np.median(a, axis=1)

array([2., 5., 8.])

In [35]:
np.median(a, axis=0)

array([4., 5., 6.])

In [38]:
c = a + b 
c

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [41]:
np.median(c, axis=0)

array([18., 20., 22.])

In [40]:
np.median((a, b), axis=0)

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [42]:
np.median((a, b), axis=1)

array([[ 4.,  5.,  6.],
       [14., 15., 16.]])

In [43]:
a 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
b 

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [47]:
c = np.arange(1, 10).reshape(3, 3, 1)
c 

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [48]:
d = np.arange(11, 20).reshape(3, 3, 1)

In [49]:
d 

array([[[11],
        [12],
        [13]],

       [[14],
        [15],
        [16]],

       [[17],
        [18],
        [19]]])

In [50]:
np.sum((c, d), axis=0)

array([[[12],
        [14],
        [16]],

       [[18],
        [20],
        [22]],

       [[24],
        [26],
        [28]]])

In [57]:
np.sum((c, d), axis=1)

array([[[12],
        [15],
        [18]],

       [[42],
        [45],
        [48]]])

In [63]:
np.sum((c,d),axis=1)

array([[[12],
        [15],
        [18]],

       [[42],
        [45],
        [48]]])

In [64]:
c

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [65]:
d

array([[[11],
        [12],
        [13]],

       [[14],
        [15],
        [16]],

       [[17],
        [18],
        [19]]])

In [66]:
a 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
count = 0
for i in a:
    for j in i:
        print(j)


1
2
3
4
5
6
7
8
9


In [71]:
for i in ar1:
    if i%2 == 0:
        print(i)

2
4


In [ ]:
count = 0
for i in a:
    for j in i:
        if j%2==0 and j > 15:
            count += 1          
print(count)

4
