In [1]:
import numpy as np


In [ ]:
#SLICING OF TWO D ARRAY
b = np.arange(1, 65).reshape(8, 8)
b 

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [3]:
b[1:3, 4:6]

array([[13, 14],
       [21, 22]])

In [4]:
b[2, 3]

np.int64(20)

In [5]:
b[3, 2]

np.int64(27)

In [6]:
b[5, 5:]

array([46, 47, 48])

In [7]:
b[1:3, 4:6]

array([[13, 14],
       [21, 22]])

In [10]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [34]:
two_D = np.arange(1, 65).reshape(4, 16)
two_D 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [35]:
two_D[0, 0], two_D[1, 1], two_D[2, 2], two_D[3, 3]

(np.int64(1), np.int64(18), np.int64(35), np.int64(52))

In [33]:
two_D[0, [3, 15]]

array([ 4, 16])

In [ ]:
#Find 4, 16
#b[0, 3], b[1, 7]


(np.int64(4), np.int64(16))

In [38]:
#Find 19, 35, 51 in two_D
two_D[[1, 2, 3], [2, 2, 2]]

array([19, 35, 51])

In [37]:
#Find 36, 54 in two_D
two_D[[2, 3], [3, 5]]

array([36, 54])

In [2]:
#Find 40, 42 in two_D

#Create a 2 D array with the starting element 25 and step should be 2
d = np.arange(25, 101, 2).reshape(2, 19)
d

array([[25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55,
        57, 59, 61],
       [63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93,
        95, 97, 99]])

In [11]:
e = np.arange(25, 201, 4).reshape(11, 4)
e 

array([[ 25,  29,  33,  37],
       [ 41,  45,  49,  53],
       [ 57,  61,  65,  69],
       [ 73,  77,  81,  85],
       [ 89,  93,  97, 101],
       [105, 109, 113, 117],
       [121, 125, 129, 133],
       [137, 141, 145, 149],
       [153, 157, 161, 165],
       [169, 173, 177, 181],
       [185, 189, 193, 197]])

In [12]:
#Find 57, 77, 97
e[[2, 3, 4], [0, 1, 2]]

array([57, 77, 97])

In [13]:
#Find 141, 65, 185, 33
e[[7, 2, 10, 0], [1, 2, 0, 2]]

array([141,  65, 185,  33])

In [14]:
#Find 57, 61, 81, 85
e[[2, 2, 3, 3], [0, 1, 2, 3]]

array([57, 61, 81, 85])

In [15]:
e[1:3, 2:4]

array([[49, 53],
       [65, 69]])