<a href="https://colab.research.google.com/github/anuragpatil811/NumPy-/blob/main/Numpy_Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [ ]:
l = [1, 2, 3, 4]

In [ ]:
a = np.array(l)

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(-1, -10, -1)

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(-1, -10, -1)

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])

In [ ]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.arange(-5, 5, 1)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.arange(-5, 1)

array([-5, -4, -3, -2, -1,  0])

In [ ]:
a = np.arange(1, 10)


In [ ]:
a.ndim

1

In [ ]:
a.shape

(9,)

In [ ]:
a.size

9

In [ ]:
b = np.arange(1, 13).reshape(2, 6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 6)

In [ ]:
b.size

12

In [ ]:
c = np.arange(1, 65).reshape(8, 8)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [ ]:
c = np.arange(1, 73).reshape(8, 9)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72]])

In [ ]:
d = np.arange(1, 73).reshape(3, 2, 12)
d

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]],

       [[49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]]])

In [ ]:
d[[0, 1, 2], [0, 0, 1], [1, 3, 11]]

array([ 2, 28, 72])

In [2]:
e = np.arange(1, 65).reshape(4, 16)
e

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [4]:
13, 14, 29, 30
e[0:2, 12:14]


array([[13, 14],
       [29, 30]])

In [6]:
e[3, 3:]

array([52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])