In [1]:
import numpy as np 

In [3]:
arr = np.array([[1, 2, 3], 
               [4, 5, 6],
               [7, 8, 9]])

In [ ]:
#arr[0:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [6]:
delete = np.delete(arr, 1, axis=1)

In [11]:
new_col = np.array([0, 0, 0])

In [12]:
arr_inserted = np.insert(delete, 1, new_col, axis=1)
print(arr_inserted)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
