In [1]:
import numpy as np
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])



In [2]:
arr[:,0] 

array([10, 40, 70])

In [3]:
arr[:,[0]] 

array([[10],
       [40],
       [70]])

In [8]:
#Vectorization
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1*2)

[ 2  4  6  8 10]


In [ ]:
#Broadcasting
A = np.array([[1,2,3],[4,5,6]])
B = np.array([10,20,30])
print(A + B)

[[11 22 33]
 [14 25 36]]
