In [1]:
import numpy as np

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])


In [3]:
#Matrix Addition
print(A + B)

[[ 6  8]
 [10 12]]


In [ ]:
#Matrix Subtraction 
print(A - B)

[[-4 -4]
 [-4 -4]]


In [ ]:
# Element-wise Matrix multiplication
print(A * B)

[[ 5 12]
 [21 32]]


In [ ]:
#The @ performs proper matrix multiplication where you multiply rows of the first matrix by columns of the second matrix
result = A @ B 
print(result)

[[19 22]
 [43 50]]


In [7]:
print(A.T)

[[1 3]
 [2 4]]


In [ ]:
#Multiplication using dot product
result_dot = np.dot(A, B)
print(result_dot)

[[19 22]
 [43 50]]


In [9]:
from numpy.linalg import det, inv
determinant_A = det(A)
print(determinant_A)

-2.0000000000000004


In [10]:
determinant_B = det(B)
print(determinant_B)

-2.000000000000005


In [11]:
inverse_A = inv(A)
inverse_B = inv(B)


In [12]:
print(inverse_A)
print(inverse_B)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.   3. ]
 [ 3.5 -2.5]]
