In [2]:
import numpy as np 

In [3]:
l = [1, 2, 3, 4]

In [4]:
a = np.array(l)

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [15]:
np.arange(-1, -10, -1)

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])

In [18]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [19]:
np.arange(-5, -1, 1)

array([-5, -4, -3, -2])

In [20]:
a = np.arange(1, 10)
a 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a.ndim 

1

In [22]:
a.shape 

(9,)

In [23]:
a.size 

9

In [24]:
# Two D Array
b = np.arange(1, 13).reshape(2, 6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [25]:
b.ndim 

2

In [26]:
b.size 

12

In [27]:
b.shape 

(2, 6)

In [31]:
c = np.arange(1, 65).reshape(8, 8)
c 

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [32]:
#3 D Arrays
np.arange(1, 65).reshape(4, 4, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

In [34]:
np.arange(1, 65).reshape(2, 16, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30],
        [31, 32]],

       [[33, 34],
        [35, 36],
        [37, 38],
        [39, 40],
        [41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50],
        [51, 52],
        [53, 54],
        [55, 56],
        [57, 58],
        [59, 60],
        [61, 62],
        [63, 64]]])

In [35]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#Indexing 
a[7]

np.int64(8)

In [40]:
a[4:8:3]

array([5, 8])

In [41]:
a[2: 5: 1]

array([3, 4, 5])

In [42]:
b 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [49]:
b = np.arange(1, 65).reshape(8, 8)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [46]:
b[1:3, 4:6]

array([[13, 14],
       [21, 22]])

In [47]:
b[3, 2]

np.int64(27)

In [48]:
b[5, 5:]

array([46, 47, 48])