In [2]:
import numpy as np 


In [ ]:
#rand() function
var = np.random.rand(4)
print(var)

[0.16161429 0.75434166 0.30515991 0.07878279]


In [4]:
var1 = np.random.rand(2, 5)
print(var1)

[[0.09958928 0.71736085 0.58574573 0.89636797 0.38654466]
 [0.72409885 0.4631089  0.51038735 0.72657686 0.09915652]]


In [5]:
#randn() function
var2 = np.random.randn(5)
print(var2)

[-1.00258415  2.04784209 -0.64271751 -1.19817252 -1.00590111]


In [6]:
#ranf() function
var3 = np.random.ranf(4)
print(var3)

[0.6389132  0.75777312 0.54643635 0.77820594]


In [7]:
#randint() function
var4 = np.random.randint(5, 20, 5)
print(var4)

[12 16  6 15 19]
