In [1]:
import numpy as np 

In [2]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])

In [3]:
print(arr1.shape)

(4,)


In [4]:
print(arr2.shape)

(2, 3)


In [5]:
print(arr3.shape)

(1, 4, 2)


In [6]:
#Statistics 
marks = np.array([56, 78, 89, 45, 92, 88, 67, 74, 81, 90])

In [7]:
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("75th Percentile:", np.percentile(marks, 75))

Mean: 76.0
Median: 79.5
Standard Deviation: 14.966629547095765
Variance: 224.0
75th Percentile: 88.75


In [8]:
temps = np.array([30, 32, 29, 35, 28, 33, 36, 31, 29, 34, 32, 30])
print("Average Temperature:", np.mean(temps))
print("Coldest Month Temperature:", np.min(temps))
print("Hottest Month Temperature:", np.max(temps))
print("Temperature Standard Deviation:", np.std(temps))

Average Temperature: 31.583333333333332
Coldest Month Temperature: 28
Hottest Month Temperature: 36
Temperature Standard Deviation: 2.43099202430247


In [9]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[2])

10
50
30


In [10]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0:4])
print(arr[1:5])
print(arr[::2])
print(arr[:4])
print(arr[2:4])
print(arr[2:])

[10 20 30 40]
[20 30 40 50]
[10 30 50]
[10 20 30 40]
[30 40]
[30 40 50]


In [11]:
matrix = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])
print(matrix[0, 1])
print(matrix[2, -1])

20
90


In [12]:
marks = np.array([45, 78, 90, 34, 67, 82, 95])
high_scores = marks[marks>60]
print(high_scores)

[78 90 67 82 95]


In [13]:
zero_arr = np.zeros((3, 3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
ones_arr = np.ones((2, 4))
print(ones_arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
evenly_spaced  = np.arange(1, 11, 2)
print(evenly_spaced)

[1 3 5 7 9]


In [16]:
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.29299939 0.51316623 0.28984832]
 [0.30730291 0.85352883 0.93888261]
 [0.96332802 0.46992355 0.69047886]]


In [17]:
arr = np.array([5, 10, 15, 20])
print(arr+5)
print(arr*2)

[10 15 20 25]
[10 20 30 40]


In [18]:
arr2 = np.array([1, 2, 3, 4])
print(arr + arr2)

[ 6 12 18 24]


In [19]:
marks = np.array([45, 78, 90, 34, 67, 82, 95])
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))

Mean: 70.14285714285714
Median: 78.0
Standard Deviation: 21.256451601663848
Variance: 451.8367346938776


In [21]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A + B)
print(A - B)
print(A * B)
print("Transpose of A:", A.T)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
Transpose of A: [[1 3]
 [2 4]]


In [26]:
result = A @ B
print(result)

[[19 22]
 [43 50]]


In [27]:
dot = np.dot(A, B)
print(dot)

[[19 22]
 [43 50]]


In [28]:
from numpy.linalg import det, inv
determinant = det(A)
print("Determinant of A:", determinant)

Determinant of A: -2.0000000000000004


In [29]:
inverse = inv(A)
print("Inverse of A:\n", inverse)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
