In [1]:
import numpy as np 

In [3]:
a = np.zeros(shape=(3, 4), dtype=int)
a 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
a.dtype

dtype('int64')

In [5]:
np.ones(shape=(3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [8]:
np.eye(3, 3, 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3, 3, 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
np.eye(3, 3, 2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.empty(shape=(3, 1))

array([[1.],
       [1.],
       [1.]])

In [14]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
np.linspace(1, 100, 8)

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

In [16]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
np.full((3, 4), fill_value=(5, 7, 8, 17))

array([[ 5,  7,  8, 17],
       [ 5,  7,  8, 17],
       [ 5,  7,  8, 17]])

In [2]:
np.random.random(12)

array([0.37404208, 0.24019282, 0.62069799, 0.80724355, 0.61252918,
       0.25081445, 0.21167444, 0.25172983, 0.81284551, 0.99120303,
       0.63307783, 0.10437012])

In [3]:
a = np.random.randint(1, 30, 10)
a

array([ 8, 26, 16, 10, 13,  2, 19, 14,  9, 27], dtype=int32)

In [4]:
np.random.choice(a, size = 4)


array([ 9, 16, 10, 19], dtype=int32)

In [5]:
np.random.permutation(a)

array([ 8, 13,  2, 14, 10, 27, 19,  9, 26, 16], dtype=int32)

In [6]:
b = np.random.randint(1, 1000, 100)
b 

array([987, 543, 900, 533, 792, 359, 748, 325, 409, 515, 631, 299, 736,
       502, 660, 529, 260, 544, 193,   3,  35, 199, 973, 411, 980, 591,
       519, 473, 577, 510, 989, 708, 611, 513, 958, 429, 625, 640, 527,
       492, 467, 332, 850, 985, 928,   2, 512, 838, 378, 523, 363, 239,
       358, 862, 551, 736, 405, 610, 844, 814, 272, 213, 388, 138, 319,
        65, 795, 102, 911, 813, 309,  62, 996, 483, 657, 670,  73, 481,
       238, 909, 761, 762, 567, 805, 582, 297, 304, 871, 410, 946, 174,
       834, 660, 217, 964,   7, 546, 372, 808, 325], dtype=int32)

In [8]:
c = np.random.permutation(b)
c

array([640, 964, 660, 309, 467, 502, 625, 911, 473, 272, 909, 591, 358,
       410, 946, 762, 838, 989, 359, 388, 543, 533, 611, 332, 325, 551,
       429, 761, 546, 862, 567, 512, 871, 660, 102, 805, 319, 193, 510,
       834,  65, 405, 138, 795, 260, 363, 985, 409, 299, 483, 814,   3,
       523, 708, 411, 996, 850, 378, 239, 958, 304, 481, 515, 844, 529,
       748, 513, 808,   2, 928, 610,  73, 670, 980, 577, 213, 792, 325,
       297,  62, 492, 582, 631, 813, 544, 973, 736, 199, 987, 519, 657,
       174, 238, 372, 527, 900,  35, 217,   7, 736], dtype=int32)

In [11]:
d = np.random.choice(c, size=25)
d 

array([519, 533,  65, 795, 567, 411, 958, 529, 989, 838, 481, 795, 483,
       838,   2, 631, 660, 138, 239, 834, 527, 808, 272, 987, 405],
      dtype=int32)

In [12]:
np.sum(d)

np.int64(14304)

In [13]:
arr = [[1, 2, 3, 4]]
ar1 = np.array(arr)
ar1

array([[1, 2, 3, 4]])

In [14]:
ar1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [15]:
arr = [[[1, 2, 3, 4]]]
ar2 = np.array(arr)
ar2

array([[[1, 2, 3, 4]]])

In [16]:
ar2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [17]:
ar2.ndim

3

In [18]:
#Convert 2D into 1D 
ar1.flatten()

array([1, 2, 3, 4])

In [19]:
#Convert 2D into 1D
ar1.ravel()

array([1, 2, 3, 4])

ValueError: cannot reshape array of size 4 into shape (1,)