In [1]:
#Zeros
import numpy as np 
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3, 4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#Ones
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [4]:
#Empty
ar_em=np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [2]:
#Range
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [3]:
#Diagonal
ar_dia = np.eye(3)
print(ar_dia)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
ar_dia = np.eye(3, 5)
print(ar_dia)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [8]:
#Linspace
ar_lin = np.linspace(1, 20, num=5)
print(ar_lin)

[ 1.    5.75 10.5  15.25 20.  ]
