In [1]:
import numpy as np

In [2]:
a = np.arange(25, 201, 4).reshape(2, 11, 2)
a 

array([[[ 25,  29],
        [ 33,  37],
        [ 41,  45],
        [ 49,  53],
        [ 57,  61],
        [ 65,  69],
        [ 73,  77],
        [ 81,  85],
        [ 89,  93],
        [ 97, 101],
        [105, 109]],

       [[113, 117],
        [121, 125],
        [129, 133],
        [137, 141],
        [145, 149],
        [153, 157],
        [161, 165],
        [169, 173],
        [177, 181],
        [185, 189],
        [193, 197]]])

In [ ]:
#INDEXING OF THREE D ARRAY

In [3]:
#Find 89
a[0, 8, 0]

np.int64(89)

In [4]:
b = np.arange(1, 65).reshape(4, 4, 4)
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

In [5]:
#Find 2, 18
b[[0, 1], [0, 0], [1, 1]]

array([ 2, 18])

In [6]:
#6, 38
b[[0, 2], 1, 1]

array([ 6, 38])

In [7]:
c = np.arange(1, 17).reshape(2, 4, 2)
c 

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [9]:
#1
c[0, 0, 0]

np.int64(1)

In [11]:
#5, 6
c[0, 2, 0:2]

array([5, 6])

In [14]:
np.arange(1, 51).reshape(2, 5, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [15]:
d = np.arange(1, 101).reshape(5, 5, 4)
d

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [17]:
#7, 45
d[[0, 2], 1, [2, 0]]

array([ 7, 45])

In [18]:
#2,  27, 84
d[[0, 1, 4], [0, 1, 0], [1, 2, 3]]

array([ 2, 27, 84])

In [19]:
#10, 32, 49, 72, 93
d[[0, 1, 2, 3, 4], 2, [1, 3, 0, 3, 0]]

array([10, 32, 49, 72, 89])

In [20]:
#8, 25, 51, 69
d[[0, 1, 2, 3], [1, 1, 2, 2], [3, 0, 2, 0]]

array([ 8, 25, 51, 69])

In [23]:
#44, 48, 52
d[2, 0:3, 3]

array([44, 48, 52])